name: lint

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip" # caching pip dependencies

      - name: Setup deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e '.[dev]'

      - name: Ruff format
        uses: chartboost/ruff-action@v1
        with:
          args: format --check

      - name: Ruff lint
        uses: chartboost/ruff-action@v1

      - name: Mypy
        run: |
          mypy src/
