name: test

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip" # caching pip dependencies

      - name: Setup deps for tests
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e '.[test]'

      - name: Test with pytest
        run: |
          pytest -v -s
